language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
dist: trusty

latex: false
compiler: clang
osx_image: xcode9


os:
- linux
- osx
env:
  global:
  - R_BUILD_ARGS="--no-build-vignettes --no-manual"
  - R_CHECK_ARGS="--as-cran --install-args=--build"
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
before_install:
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- codename=`linux_codename`;
- if [ "${codename}" = "trusty" ];
  then
    start_xvfb ;
  fi  
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
- remove_neuroc_packages
- export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
- x=`export_clang_cxx`; eval ${x}
- echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
- echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
- clang_cxx
- export cmake_version="3.14"
- cmake --version
- x=`cmake_setup`; echo "${x}"; eval ${x};
- cmake --version
- glu_header ;
- export ants_user=neuroconductor
- echo "Installing Missing Deps ITKR"
- install_missing_remote_deps ${ants_user}/ITKR
- gh_binary_install ${ants_user}/ITKR ;
- if [[ "${PACKAGE_NAME}" != "ITKR" ]]; then echo "Installing Missing Deps ANTsRCore"
  ; install_missing_remote_deps ${ants_user}/ANTsRCore; gh_binary_install ${ants_user}/ANTsRCore
  ; fi
- if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" ]]; then echo
  "Installing Missing Deps ANTsR" ; install_missing_remote_deps ${ants_user}/ANTsR
  ; gh_binary_install ${ants_user}/ANTsR ; fi
- if [[ "${PACKAGE_NAME}" == "ANTsR" ]]; then export _R_CHECK_FORCE_SUGGESTS_=false ;
  fi
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- echo $PATH ;
- install_deps_no_suggests
script:
- x=`export_clang_cxx`; eval ${x}
- travis_wait 100 R CMD build ${R_BUILD_ARGS} .
- rm -f travis_wait*.log
- PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
- ls
- travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
- rm -f travis_wait*.log
- if [[ $CHECK_RET -ne 0 ]];
  then
    echo "R CMD check failed"; 
    check_fail; 
    exit 1; 
  fi  
- check_warnings
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- dump_logs
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then rm -f *.tar.gz; fi
after_deploy:
- if [[ "${PACKAGE_NAME}" != "ANTsR" && "${PACKAGE_NAME}" != "ITKR" && "${PACKAGE_NAME}" != "ANTsRCore" ]]; Rscript -e 'covr::coveralls(type = "all")' ; fi


deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ATTq8B5qry2hLOsbYRXb6kwG3O0JgSQjmkP9aCsiLkZbBx1ivFIsy8WTGg6UGvSOjY3DMNYR266oyIxKutGmnLFh38C8bVoGdquhDSOAXUjeb4Mz3aNglXHOxGhcD/xdlcJToGFkxwYAuEgTHoAaRo6KQUKV5AqEO8Vw1qx9DVfg8RdfrlkH7CXoxUr65SFvBsEMuwXH9VlLuPkMd0HrRWWeo255ASltN5N9l5EEFZQ+DGwyeRum1HwW7VBuJvIuWnOvZVcTwxYw6vqu4FEWinUbtnW9GpQ/FUjFj6DlA651mA0LuK3RrmngGhdbaJn51ct8NdH7bnkaS6/UuJT02Yzqhj4D7pQK6uLosVO15oh1RySOJygE1rVS9EtufRxgH4fqa5YQqvnczTKwh0WHpt3EDuEKhLdfQxEjr+daEr+XqFofdCBaRUWU9YjeXy77hxEbTi9EN7IHNIj7yqeOI2yVsCvYVhl7C9n72ndJTDw5CRIXH6LL4rBaLzMfrhq4uIrq6F3y1nRMVyEpH2f1C670DH3OP9JcMTYaFeWs1XLsd9pCGrale7PGHnnQeBp9lqdWieGtjhQvskZbnsy9OKqipV20//+GZtmabQIS9OzCctUbxWvOAdu2g067XgBA/sRE4t/pFaK+vH+TS7WG8800oJAtZoNj983p376xkvs=
  file_glob: true
  file: ${PACKAGE_NAME}*.t*gz
  on:
    tags: true